### ISSUE TITLE
Module 7 content does not load

### ISSUE THREAD

**Issue by auntysocial** [creativecommons/cc-cert-map#13]
All the objectives are stuck in loading spins.

![spin](https://cloud.githubusercontent.com/assets/18296835/16500143/3a03999a-3eb8-11e6-883e-22d446aff913.jpg)

It looks like there is a typo in the directory name??

https://github.com/creativecommons/cc-cert-map/tree/gh-pages/content/moudle7

**Comment by cogdog** [comment]
Easy fix, just need to edit directory name, and sync up. Thanks.

**Comment by cogdog** [comment]
All fixed! Who me, make a typo?

![working7](https://cloud.githubusercontent.com/assets/463038/16501867/772cba06-3ec0-11e6-9a13-a88183e1ad3b.jpg)
