### ISSUE TITLE
unit count is wrong in summit quest sentence

### ISSUE THREAD

**Issue by Stephen-Gates** [creativecommons/cc-cert-map#23]
the sentence about the summit quest on the [copyright index page](https://github.com/creativecommons/cc-cert-core/blob/master/contents/copyright/index.md) mentions `four units` - there are five.

> On completion of these five units the final summit quest combines learning from across all **four units** into one final assignment for the whole module.

**Comment by cogdog** [comment]
This whole structure for the quests is in progress of being redone. Waiting on content
