### ISSUE TITLE
Contributor licence agreement for Quest Bank

### ISSUE THREAD

**Issue by Stephen-Gates** [creativecommons/cc-cert-map#27]
At the end of [some modules](https://certificates.creativecommons.org/core/v022/contents/copyright/other-ip/) you are asked to complete [a quest](https://certificates.creativecommons.org/quests/assignments/poetic-ip/).

It is not clear under what licence contributions are made. There should be a notice beside the Post Comment button that says all comments posted are contributed under some licence or waiver.

If people contribute via their work at the supplied URL, then they can apply their licence on that site.

**Comment by cogdog** [comment]
This is in progress. I am waiting a final decision on the certification content to be CC BY or CC BY-SA and then need to update quest bank to be in sync. Flagging for closing later

**Comment by kgodey** [comment]
This seems out of date.

**Comment by cogdog** [comment]
TBH this repo should be closed, archived, deleted. It was for an infrastructure approach to the certificates that was never used.

**Comment by kgodey** [comment]
@cogdog thanks, good to know! is that also true for these repos?
https://github.com/creativecommons/cc-cert-gov
https://github.com/creativecommons/cc-cert-edu
https://github.com/creativecommons/cc-cert-lib

**Comment by cogdog** [comment]
Yes! The other ones I worked with are already archived, e,g. https://github.com/cc-archive/cc-cert-core-hugo
