### ISSUE TITLE
pop goes the weasel link

### ISSUE THREAD

**Issue by Stephen-Gates** [creativecommons/cc-cert-map#30]
The first song sung in the video linked [here](https://github.com/creativecommons/cc-cert-core/blame/master/contents/copyright/public-domain.md#L36) is pop goes the weasel, followed by row, row, row, your boat, B.I.N.G.O., ... 

Twinkle Star is at https://youtu.be/bW0E_sncNic?t=8m33s 

Perhaps replace Twinkle with Pop in the text

**Comment by cogdog** [comment]
Fixed with pull request
