### ISSUE TITLE
What is Protected Link Broken

### ISSUE THREAD

**Issue by cogdog** [creativecommons/cc-cert-map#34]
In [Copyright Basics](https://github.com/creativecommons/cc-cert-core/blob/master/contents/copyright/basics.md) under **The Types of Works Protected by Copyright** bad link for "What is Protected"

http://smartcopying.edu.au/copyright-guidelines/copyright

Is this the appropriate substitute?
http://smartcopying.edu.au/copyright-guidelines/what-can-i-copy-communicate-

(mostly doing this to get un cycle if using GH issues)

**Comment by kamilsliwowski** [comment]
This one will be more accurate: http://smartcopying.edu.au/copyright-guidelines/copyright---a-general-overview/1-3-what-is-protected-(types-of-works)
