### ISSUE TITLE
Suggestions for Objective 1.4.2 Appreciate public domain

### ISSUE THREAD

**Issue by auntysocial** [creativecommons/cc-cert-map#4]
_use template for edit suggestions to map; for any other issues, just wipe this stuff out_
## Suggested wording for the introductory sentence (1-2 sentences):

Include some value propositions that include examples of where public domain content has been put to good use.
## Suggested Open Educational Resource(s) for this Objective:

_Include the title, URL, name of publishing organization/person, and license (if known); copy if you need more_
- Title: Value of the Public Domain
- URL: http://rufuspollock.org/papers/value_of_public_domain.ippr.pdf
- Published by: Rufus Pollack, Institute for Public Policy Research www.ippr.org
- License: not stated
- Title:
- URL: 
- Published by:
- License:
- Title:
- URL: 
- Published by:
- License:
## Suggested idea/activity to assess achievement of this objective:

_Please be as detailed as possible and make sure it demonstrates in practice the objective_

The activity should be explained clearly here along with suggestions for what would be needed to assess its completion

**Comment by cogdog** [comment]
Resource added, not enough specificity in suggested wording to warrant change
