### ISSUE TITLE
Bump Upload Limit on Certification Wordpress site

### ISSUE THREAD

**Issue by cogdog** [creativecommons/cc-cert-map#6]
(putting here until we get a repo).

Please increase the PHP upload limit for certifications.creativecommons.org  to 10 or 20 Mb

**Comment by rheaplex** [comment]
Bumped to 20, please try now. :-)

**Comment by cogdog** [comment]
Works like a champ. Thanks

**Comment by rheaplex** [comment]
Awesome!
